//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softcode.GTex.ApplicationService.Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class GeneralAccountModel
    {
        public int GeneralAccountId { get; set; }
        public decimal ControlCode { get; set; }
        public decimal AccountCode { get; set; }
        public string AccountName { get; set; }
        public string AccountType { get; set; }
        public string CompId { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
