//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softcode.GTex.ApplicationService.Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class VoucherModel
    {
       
        public int VoucherId { get; set; }
        public int VoucherTypeId { get; set; }
        public int CompanySectorId { get; set; }
        public string VoucherRefId { get; set; }
        public string voucherNo { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string Narration { get; set; }
        public string CompId { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual CompanySectorModel CompanySector { get; set; }
        public virtual VoucherTypeModel VoucherType { get; set; }
        public virtual ICollection<VoucherDetailModel> VoucherDetails { get; set; }
    }
}
