//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softcode.GTex.ApplicationService.Accounting.Models
{
    using System;
    using System.Collections.Generic;
    
    public  class VoucherDetailModel
    {
        public int VoucherDetailId { get; set; }
        public int VoucherId { get; set; }
        public int CostCenterId { get; set; }
        public double DebitAmount { get; set; }
        public double CreditAmount { get; set; }
        public string Description { get; set; }
        public string CompId { get; set; }
    
        public virtual CostCenterModel CostCenter { get; set; }
        public virtual VoucherModel Voucher { get; set; }
    }
}
